### ISSUE TITLE
Pump Disconnection not working

### ISSUE THREAD

**Issue by Dathomas207** [piotti/robot-control#7]
earching for a path...

Acquiring pipe fitting...
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 144, in move_pip
e_thread
    result = robot_use.movePipe(nearNum, farNum, direction)
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 416,
in movePipe
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 286, in
run
    data = self._get_data()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 333, in
_get_data
    tmp = self._s_secondary.recv(1024)
timeout: timed out

Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 137, in move_rea
ctor_thread
    if robot_use.moveReactor(storeNum, bayNum, direction, reactorType):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 162,
in moveReactor
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5

Searching for a path...

Acquiring pipe fitting...

Acquiring pipe fitting...
Found path to joint angles: (-2.0596957866386543, 3.7985276149482314, 4.01965023
40076128, -4.6716498667767787, 1.5428240456877051, 3.1289326662341281)

Acquiring pipe fitting...
Moving...

Acquiring pipe fitting...
Searching for a path...
Searching for a path...
Searching for a path...
Searching for a path...
Found path to joint angles: (-2.0596957866386543, 3.869512335283086, 4.000440360
090197, -4.723424713194218, 1.5428240456877051, 3.1289326662341281)
Moving...
Found path to joint angles: (-2.0596957866386543, 3.9414843598841429, 3.98540373
51978588, -4.7803601129029367, 1.5428240456877051, 3.1289326662341281)Found path
 to joint angles: (-2.0596957866386543, 4.0139631015126449, 3.9747041402856915,
-4.8421392596192714, 1.5428240456877051, 3.1289326662341281)T
raceback (most recent call last):

  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 125,
 in moveTo
    pose = self.movexs("movej", points, acc= acc, vel = vel,radius = radius)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 218, in _
wait_for_move
    dist = self._get_dist(target, joints)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 234, in _
get_dist
    return self._get_lin_dist(target)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 31, in _get
_lin_dist
    pose = URRobot.getl(self, wait=True)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 323, in g
etl
    pose = self.secmon.get_cartesian_info(wait)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 348, in
get_cartesian_info
    self.wait()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5
Move Failed: Did not receive a valid data packet from robot in 0.5
Move between near pipe 5 and far pipe 7 in direction 1 failed
wrote!
wrote!
handled exception in resume
Found path to joint angles: (-2.0596957866386543, 4.0863647742569063, 3.96846653
13054581, -4.9083033233832989, 1.5428240456877051, 3.1289326662341281)
Moving...
Moving...
Moving...
Found path to joint angles: (-2.0661848108516327, 4.4093625057552135, 4.00683625
81227461, -5.258262427489667, 1.5503385799667262, 3.125864498288311)
Moving...
Move complete!
Moving...
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 125,
 in moveTo
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
    pose = self.movexs("movej", points, acc= acc, vel = vel,radius = radius)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0844736306888, threshold is 0.0838304624631, target is [-0.22649123 -0
.18165951  0.18653493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
2304628838618671, -0.187619521919467, 0.27006072777274337, 1.5239157001707444, -
0.38629248848011466, -0.41701293872555134]
 M   raise RobotException("Goal not reached but no program has been running for
{} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".forma
t(timeout, dist, threshold, target, URRobot.getl(self)))
ove Failed: Goal not reached but no program has been running for 6 seconds. dist
 is 0.0844736306888, threshold is 0.0838304624631, target is [-0.22649123 -0.181
65951  0.18653493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.2304
628838618671, -0.187619521919467, 0.27006072777274337, 1.5239157001707444, -0.38
629248848011466, -0.41701293872555134]R
obotException: Goal not reached but no program has been running for 6 seconds. d
ist is 0.0469382925341, threshold is 0.0410312171806, target is [-0.25514612 -0.
22671322  0.27131066  1.52579543 -0.37786993 -0.41464328], current pose is [-0.2
304628838618671, -0.187619521919467, 0.27006072777274337, 1.5239157001707444, -0
.38629248848011466, -0.41701293872555134]
Move Failed: Goal not reached but no program has been running for 6 seconds. dis
t is 0.0469382925341, threshold is 0.0410312171806, target is [-0.25514612 -0.22
671322  0.27131066  1.52579543 -0.37786993 -0.41464328], current pose is [-0.230
4628838618671, -0.187619521919467, 0.27006072777274337, 1.5239157001707444, -0.3
8629248848011466, -0.41701293872555134]
 Move between near pipe 4 and far pipe 6 in direction 1 failed
Move between near pipe 4 and far pipe 1 in direction 1 failed
wrote!
handled exception in resume
wrote!
handled exception in resume
Traceback (most recent call last):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0456874977657, threshold is 0.0365463311187, target is [-0.22649123 -0
.18165951  0.22613493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
2304547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078,
-0.38626980063891136, -0.4170042202173633]
Move Failed: Goal not reached but no program has been running for 6 seconds. dis
t is 0.0456874977657, threshold is 0.0365463311187, target is [-0.22649123 -0.18
165951  0.22613493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.230
4547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078, -0.
38626980063891136, -0.4170042202173633]
Traceback (most recent call last):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
 M File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mo
vexs
ove between near pipe 1 and far pipe 2 in direction 1 failed
   return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0714363424637, threshold is 0.0571503385852, target is [-0.22649123 -0
.18165951  0.19973493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
2304547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078,
-0.38626980063891136, -0.4170042202173633]
Move Failed: Goal not reached but no program has been running for 6 seconds. dis
t is 0.0714363424637, threshold is 0.0571503385852, target is [-0.22649123 -0.18
165951  0.19973493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.230
4547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078, -0.
38626980063891136, -0.4170042202173633]
Move between near pipe 3 and far pipe 5 in direction 1 failed
Traceback (most recent call last):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0584893942381, threshold is 0.0467908555096, target is [-0.22649123 -0
.18165951  0.21293493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
2304547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078,
-0.38626980063891136, -0.4170042202173633]
Move Failed: Goal not reached but no program has been running for 6 seconds. dis
t is 0.0584893942381, threshold is 0.0467908555096, target is [-0.22649123 -0.18
165951  0.21293493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.230
4547391699346, -0.18762811584945968, 0.2700524219033022, 1.5239839052166078, -0.
38626980063891136, -0.4170042202173633]
Move between near pipe 2 and far pipe 3 in direction 1 failed
wrote!
handled exception in resume
wrote!
handled exception in resume
wrote!
handled exception in resume

**Comment by Dathomas207** [comment]
The program is skipping from one tubing to the next without finishing the placement. The robot will actually complete the move of the pipe fitting once the queue calls a reactor move.

**Comment by Dathomas207** [comment]
completely looks a like a robot communication issue as the PUMPCONNECT works well.

**Comment by Dathomas207** [comment]
wrote!
moving pipe
(2, 3) (0, 0) 1
wrote!
wrote!
moving reactor
(1, 1) (0, 4) -1 long False False None

Acquiring pipe fitting...
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 144, in move_pip
e_thread
    result = robot_use.movePipe(nearNum, farNum, direction)
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 416,
in movePipe
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5

Searching for a path...
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 286, in
run
    data = self._get_data()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 333, in
_get_data
    tmp = self._s_secondary.recv(1024)
timeout: timed out

Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 144, in move_pip
e_thread
    result = robot_use.movePipe(nearNum, farNum, direction)
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 416,
in movePipe
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5

Exception in thread Thread-27:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 286, in
run
    data = self._get_data()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 333, in
_get_data
    tmp = self._s_secondary.recv(1024)
timeout: timed out

Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 144, in move_pip
e_thread
    result = robot_use.movePipe(nearNum, farNum, direction)
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 416,
in movePipe
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5

Exception in thread Thread-28:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 286, in
run
    data = self._get_data()
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 333, in
_get_data
    tmp = self._s_secondary.recv(1024)
timeout: timed out

Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner

    self.run()
  File "C:\Users\ROB\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ROB\Desktop\robot-control\controller.py", line 137, in move_rea
ctor_thread
    if robot_use.moveReactor(storeNum, bayNum, direction, reactorType):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_use.py", line 162,
in moveReactor
    rob = UR3(config["IP"],config["wallPoints"])
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 14,
in __init__
    urx.Robot.__init__(self, IP)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 27, in __in
it__
    URRobot.__init__(self, host, use_rt)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 38, in __
init__
    self.secmon = ursecmon.SecondaryMonitor(self.host)  # data from robot at 10H
z
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 252, in
__init__
    self.wait()  # make sure we got some data before someone calls us
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\ursecmon.py", line 344, in
wait
    raise TimeoutException("Did not receive a valid data packet from robot in {}
".format(timeout))
TimeoutException: Did not receive a valid data packet from robot in 0.5

Found path to joint angles: (-2.0596957866386543, 3.7985276149482314, 4.01965023
40076128, -4.6716498667767787, 1.5428240456877051, 3.1289326662341281)
Moving...

Acquiring pipe fitting...
Searching for a path...

Acquiring pipe fitting...

Acquiring pipe fitting...
Searching for a path...
Searching for a path...
Found path to joint angles: (-2.0596957866386543, 3.869512335283086, 4.000440360
090197, -4.723424713194218, 1.5428240456877051, 3.1289326662341281)
Moving...
Found path to joint angles: (-2.0596957866386543, 3.9414843598841429, 3.98540373
51978588, -4.7803601129029367, 1.5428240456877051, 3.1289326662341281)
Moving...
Found path to joint angles: (-2.0596957866386543, 4.0139631015126449, 3.97470414
02856915, -4.8421392596192714, 1.5428240456877051, 3.1289326662341281)
Moving...
Move complete!
Moving...
Move complete!
Moving...
Move complete!
Moving...
Move complete!
Moving...
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
  File "C:\Users\ROB\Dropbox\Robotic_Toolbox\Robot\UR3\robot_move.py", line 139,
 in moveTo
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
    pose = np.array(self.movexs('movej', points[nearest_point:], acc=acc, vel =
vel, radius = radius))
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\robot.py", line 194, in mov
exs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
    return URRobot.movexs(self, command, new_poses, acc, vel, radius, wait=wait,
 threshold=threshold)
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 369, in m
ovexs
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
  File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in _
wait_for_move
    self._wait_for_move(target=pose_list[-1], threshold=threshold)
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0530634076778, threshold is 0.0105453080459, target is [-0.22649123 -0
.18165951  0.19973493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
24772270419516662, -0.16920944786713552, 0.21219150645137622, 1.541051740058807,
 -0.35139408802687416, -0.39094506739196355]
 M File "C:\Users\ROB\Anaconda2\lib\site-packages\urx\urrobot.py", line 226, in
_wait_for_move
ove Failed: Goal not reached but no program has been running for 6 seconds. dist
 is 0.0530634076778, threshold is 0.0105453080459, target is [-0.22649123 -0.181
65951  0.19973493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.2477
2270419516662, -0.16920944786713552, 0.21219150645137622, 1.541051740058807, -0.
35139408802687416, -0.39094506739196355]
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
    raise RobotException("Goal not reached but no program has been running for {
} seconds. dist is {}, threshold is {}, target is {}, current pose is {}".format
(timeout, dist, threshold, target, URRobot.getl(self)))
RobotException: Goal not reached but no program has been running for 6 seconds.
dist is 0.0645785759444, threshold is 0.0316651164475, target is [-0.22649123 -0
.18165951  0.17333493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.
24772270419516662, -0.16920944786713552, 0.21219150645137622, 1.541051740058807,
 -0.35139408802687416, -0.39094506739196355]
RMobotException: Goal not reached but no program has been running for 6 seconds.
 dist is 0.0576091906964, threshold is 0.0211051643137, target is [-0.22649123 -
0.18165951  0.18653493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0
.24772270419516662, -0.16920944786713552, 0.21219150645137622, 1.541051740058807
, -0.35139408802687416, -0.39094506739196355]
ove Failed: Goal not reached but no program has been running for 6 seconds. dist
 is 0.0645785759444, threshold is 0.0316651164475, target is [-0.22649123 -0.181
65951  0.17333493  1.53095813 -0.39446681 -0.4156515 ], current pose is [-0.2477
2270419516662, -0.16920944786713552, 0.21219150645137622, 1.541051740058807, -0.
35139408802687416, -0.39094506739196355]Move between near pipe 3 and far pipe 5
in direction 1 failedMove Failed: Goal not reached but no program has been runni
ng for 6 seconds. dist is 0.0576091906964, threshold is 0.0211051643137, target
is [-0.22649123 -0.18165951  0.18653493  1.53095813 -0.39446681 -0.4156515 ], cu
rrent pose is [-0.24772270419516662, -0.16920944786713552, 0.21219150645137622,
1.541051740058807, -0.35139408802687416, -0.39094506739196355]


Move between near pipe 5 and far pipe 7 in direction 1 failedMove between near p
ipe 4 and far pipe 6 in direction 1 failed

wrote!
wrote!
handled exception in resume
wrote!
handled exception in resume
wrote!
handled exception in resume

**Comment by Dathomas207** [comment]
The commands work when called individually.
